# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Asana < Formula
  desc "A command-line interface for managing Asana directly from your terminal."
  homepage "https://github.com/timwehrle/asana"
  version "1.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/timwehrle/asana/releases/download/v1.2.0/asana_Darwin_x86_64.tar.gz"
      sha256 "dd5e6f611dfc5f663676de26f8208c4a60c2d2219bae491bece15e40140ba0b2"

      def install
        bin.install "asana"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/timwehrle/asana/releases/download/v1.2.0/asana_Darwin_arm64.tar.gz"
      sha256 "62e7f8783829cec62001964c82c2fd4cb4d732ae6cc6e0eee973514c8a5c3798"

      def install
        bin.install "asana"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/timwehrle/asana/releases/download/v1.2.0/asana_Linux_x86_64.tar.gz"
      sha256 "23a92a5ddcc5abcf0f1d0df1c5ffee032dcfe3e9f6dbce83a2b0086e164d2cad"
      def install
        bin.install "asana"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/timwehrle/asana/releases/download/v1.2.0/asana_Linux_armv6.tar.gz"
      sha256 "80bd0b2a9261e8ba6f7c80ac9c6153b0366b761953d6e233c15e8a1d802bab69"
      def install
        bin.install "asana"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/timwehrle/asana/releases/download/v1.2.0/asana_Linux_arm64.tar.gz"
      sha256 "91b624bdf4d0ef25ce177138a6bba2f5b8641d35a5a7461ec9cf87155e85bcd6"
      def install
        bin.install "asana"
      end
    end
  end
end
