# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Asana < Formula
  desc "A command-line interface for managing Asana directly from your terminal."
  homepage "https://github.com/timwehrle/asana"
  version "0.1.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/timwehrle/asana/releases/download/v0.1.5/asana_Darwin_x86_64.tar.gz"
      sha256 "0e0537500bea97283537f58576a1ae283355db5ff3cf158d80895716bde8e6b1"

      def install
        bin.install "asana"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/timwehrle/asana/releases/download/v0.1.5/asana_Darwin_arm64.tar.gz"
      sha256 "99f7a061ec636df73c74a5b4efd5cc7fab0625b58a377c1d47e6097cab3440d9"

      def install
        bin.install "asana"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/timwehrle/asana/releases/download/v0.1.5/asana_Linux_x86_64.tar.gz"
        sha256 "4b5a44694a509e08b886a59def95947a9cf27b9d51893a17cda67bb5dc196f70"

        def install
          bin.install "asana"
        end
      end
    end
    if Hardware::CPU.arm?
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/timwehrle/asana/releases/download/v0.1.5/asana_Linux_armv6.tar.gz"
        sha256 "116147ca911c294412756ed2c4b08dca53eb1e86864f02c79d2faf7e919f2a84"

        def install
          bin.install "asana"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/timwehrle/asana/releases/download/v0.1.5/asana_Linux_arm64.tar.gz"
        sha256 "6d890a26f162debc17d2086a99f1ad61391d5694d09a0c9fd5579e3cf752248b"

        def install
          bin.install "asana"
        end
      end
    end
  end
end
